// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {startTag, commentContent, elementContext} from "./tokens.js"
import {NodeProp} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "'hOVQTOOOeQYO'#CcOmQ`O'#CfOrQTO'#CeOOQP'#Ce'#CeOOQP'#C{'#C{OOQP'#Cq'#CqQVQTOOOOQQ'#Cr'#CrO!aQYO,58}OOQP,58},58}O!iQpO,59QO!tQ`O'#CnOOQP'#DV'#DVOOQP'#Cv'#CvOrQTO,59PO!yQ`O'#CoOOQP,59P,59POOQP-E6o-E6oOOQQ-E6p-E6pOOQP1G.i1G.iO#OQpO'#ChOOQO'#Cs'#CsO#^QpO1G.lOOQP1G.l1G.lOOQP1G.v1G.vO#iQWO,59YOOQP-E6t-E6tOOQP1G.k1G.kO#nQWO,59ZO#sQWO,59SOOQO-E6q-E6qOOQP7+$W7+$WOOQP7+$b7+$bOOQP1G.t1G.tOOQP1G.u1G.uO#{Q!bO'#DPO$^Q#tO'#DSOOQO'#Ck'#CkOOQO1G.n1G.nOOQO'#Ct'#CtO$oQ!bO,59kOOQO,59k,59kOOQO'#Cu'#CuO%QQ#tO,59nOOQO,59n,59nOOQO-E6r-E6rOOQO1G/V1G/VOOQO-E6s-E6sOOQO1G/Y1G/Y",
  stateData: "%h~OnOS~OPQOUTOWTOqPO~OlWOpYO~OZZO~OPQOQ`OR[OS]OU]OW]O`]Oa]OqPO~OlWOpdO~O]eOrhOziO~OZjO~OZmO~O^nO][Xr[Xz[X~O]eOrpOzqO~OrrO~OrsO~OttOwuO~OWxO`xOaxOtzOuxO~OW{O`{Oa{Ow}Ox{O~OWxO`xOaxOt!POuxO~OW{O`{Oa{Ow!ROx{O~OuxUx~",
  goto: "#ozPPPPPPP{P{!TP!ZPP!_PP!P!b!h!n!t!z#Q#W#^PPPP#dPPP#hPP#hPP#kSTOVT]R_XRORV_TfZgRwnQaRRl_XSORV_QVORbVQXPRcXQgZRogQytR!OyQ|uR!Q|Q_RRk_TUOVRvnT^R_",
  nodeNames: "⚠ StartTag StartCloseTag StartCloseTag StartCloseTag Document Text Comment Macro Element OpenTag TagName Attribute AttributeName Is AttributeValue EntityReference CharacterReference MismatchedCloseTag CloseTag SelfClosingTag",
  maxTerm: 42,
  context: elementContext,
  nodeProps: [
    [NodeProp.closedBy, 1,"SelfCloseEndTag EndTag",10,"CloseTag"],
    [NodeProp.openedBy, 19,"OpenTag"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 6,
  tokenData: "9z~R}OX$OXZ'eZ])W]^'e^p$Opq'eqr$Ors+Zst$Otu+vuv$Ovw,rwx._x}$O}!O.}!O!P$O!P!Q4Z!Q![2P![!^$O!^!_5w!_!`8b!`!a9V!a!c$O!c!}2P!}#R$O#R#S2P#S#T$O#T#o2P#o#y$O#y#z)W#z$f$O$f$g)W$g#BY$O#BY#BZ)W#BZ$IS$O$IS$I_)W$I_$I|$O$I|$JO)W$JO$JT$O$JT$JU)W$JU$KV$O$KV$KW)W$KW&FU$O&FU&FV)W&FV~$O!R$XWu`xpUPOr$Ors$qst$Ouv$Owx%{x!^$O!^!_&z!_~$Oa$xUu`UPOt$quv$qwx%[x!^$q!^!_%m!_~$qP%aSUPOt%[uv%[w!^%[!_~%[`%rRu`Ot%muv%mx~%mq&SVxpUPOr%{rs%[st%{uv%{w!^%{!^!_&i!_~%{p&nSxpOr&ist&iuv&iw~&i!Q'RUu`xpOr&zrs%mst&zuv&zwx&ix~&z~'lhn~UPOX%[X^'e^p%[pq'eqt%[uv%[w!^%[!_#y%[#y#z'e#z$f%[$f$g'e$g#BY%[#BY#BZ'e#BZ$IS%[$IS$I_'e$I_$I|%[$I|$JO'e$JO$JT%[$JT$JU'e$JU$KV%[$KV$KW'e$KW&FU%[&FU&FV'e&FV~%[~)cln~u`xpUPOX$OX^)W^p$Opq)Wqr$Ors$qst$Ouv$Owx%{x!^$O!^!_&z!_#y$O#y#z)W#z$f$O$f$g)W$g#BY$O#BY#BZ)W#BZ$IS$O$IS$I_)W$I_$I|$O$I|$JO)W$JO$JT$O$JT$JU)W$JU$KV$O$KV$KW)W$KW&FU$O&FU&FV)W&FV~$O!T+dUwru`UPOt$quv$qwx%[x!^$q!^!_%m!_~$q~+}Tu`xp}!O,^!Q![,^!c!},^#R#S,^#T#o,^~,cTW~}!O,^!Q![,^!c!},^#R#S,^#T#o,^~,uTOp-Uqs-Ust-mt!]-U!^~-U~-XTOp-Uqs-Ut!]-U!]!^-h!^~-U~-mO`~~-pROp-yq!]-y!^~-y~-|SOp-yq!]-y!]!^.Y!^~-y~._Oa~!T.hVtbxpUPOr%{rs%[st%{uv%{w!^%{!^!_&i!_~%{!a/[b]WZSu`xpUPOr$Ors$qst$Ouv$Owx%{x}$O}!O0d!O!Q$O!Q![2P![!^$O!^!_&z!_!c$O!c!}2P!}#R$O#R#S2P#S#T$O#T#o2P#o~$O!a0qd]WZSu`xpUPOr$Ors$qst$Ouv$Owx%{x}$O}!O2P!O!Q$O!Q![2P![!^$O!^!_&z!_!`$O!`!a3f!a!c$O!c!}2P!}#R$O#R#S2P#S#T$O#T#o2P#o~$O!_2^b]WZSu`xpUPOr$Ors$qst$Ouv$Owx%{x}$O}!O2P!O!Q$O!Q![2P![!^$O!^!_&z!_!c$O!c!}2P!}#R$O#R#S2P#S#T$O#T#o2P#o~$O!T3qWpQu`xpUPOr$Ors$qst$Ouv$Owx%{x!^$O!^!_&z!_~$O!Z4dYu`xpUPOr$Ors$qst$Ouv$Owx%{x!^$O!^!_&z!_!`$O!`!a5S!a~$O!Z5_WzWu`xpUPOr$Ors$qst$Ouv$Owx%{x!^$O!^!_&z!_~$O!R6OVu`xpOq&zqr6ers%mst&zuv&zwx&ix~&z!R6lWu`xpOr&zrs%mst&zuv&zwx&ix}&z}!O7U!O~&z!R7]Wu`xpOr&zrs%mst&zuv&zwx&ix}&z}!O7u!O~&z!R8OUqPu`xpOr&zrs%mst&zuv&zwx&ix~&z!Z8mW^Wu`xpUPOr$Ors$qst$Ouv$Owx%{x!^$O!^!_&z!_~$O!]9bWrYu`xpUPOr$Ors$qst$Ouv$Owx%{x!^$O!^!_&z!_~$O",
  tokenizers: [startTag, commentContent, 0, 1, 2, 3, 4, 5],
  topRules: {"Document":[0,5]},
  tokenPrec: 203
})
