// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {startTag, commentContent, elementContext} from "./tokens.js"
import {NodeProp} from "@lezer/common"
export const parser = LRParser.deserialize({
  version: 13,
  states: "*[OQOTOOO]OYO'#CdOeO`O'#CfO!OOTO'#CeOOOP'#Ce'#CeOOOP'#Cx'#CxOOOP'#Co'#CoQQOTOOOOOQ'#Cp'#CpO!VOYO,59OOOOP,59O,59OO!_OpO,59QO!mO`O'#ClOOOP'#DT'#DTOOOP'#Cu'#CuO!rOTO,59PO!yO`O'#CmOOOP,59P,59POOOP-E6m-E6mOOOQ-E6n-E6nOOOP1G.j1G.jOOOO'#Cq'#CqO#ROpO1G.lO#aOpO'#ChOOOO'#Cr'#CrO#rOpO1G.lOOOP1G.l1G.lOOOP1G.t1G.tO#}OWO,59WOOOP-E6s-E6sOOOP1G.k1G.kO$SO`O,59XO$[OWO,59XOOOO-E6o-E6oO$dOpO7+$WOOOP7+$W7+$WOOOP7+$`7+$`O$oOpO,59SO%QOWO,59SOOOO-E6p-E6pOOOP1G.r1G.rO%]OWO1G.sO%]OWO1G.sOOOP1G.s1G.sOOOP<<Gr<<GrOOOP<<Gz<<GzO%QOWO1G.nO%QOWO1G.nO%eO!bO'#C}O%mO#tO'#DQOOOO'#Ck'#CkO%uOpO1G.nO&TOWO7+$_OOOP7+$_7+$_O%QOWO7+$YO&]OpO7+$YOOOO'#Cs'#CsO&kO!bO,59iOOOO,59i,59iOOOO'#Ct'#CtO&sO#tO,59lOOOO,59l,59lO&]OpO7+$YOOOP<<Gy<<GyO&{OpO<<GtO&{OpO<<GtOOOO-E6q-E6qOOOO1G/T1G/TOOOO-E6r-E6rOOOO1G/W1G/WO'ZOpOAN=`",
  stateData: "'i~OPQOVTOnPO~OkWOmYO~OZZO~OPQOQ`OS[OT]OV]OnPO~ORaO~PjOkWOmdO~O]gOojOpeOxkO~OZlO~ORnO~PjOZpOpeO~O]gOosOpeOxtO~O^vOpeO][Xo[Xx[X~O]gOosOxtO~OoxO~OZyOpeO~Oo{OpeO~O]gOo|Ox}O~O^!OOpeO][ao[ax[a~OpeOr!QOu!RO~Oo!VOpeO~Or![Os!YO~Ou!_Ov!]O~OpeO][io[ix[i~Oo!aOpeO~OpeO][qo[qx[q~Or!eOs!YO~Ou!gOv!]O~OpeO][yo[yx[y~OpeO][!Ro[!Rx[!R~O",
  goto: "$yxPPPPPPPPyy!RP!XPP!_}!i!o!u!{#R#}$X$_$ePP$kPPPP$oPP$oPP$uSTOVT]R_XRORV_XhZfirQ!TvS!X!O!PR!b!WQaRRn_XSORV_QVORbVQXPRcXQfZQo`dqfouz!P!U!W!`!c!hQugQzpQ!PvQ!UyQ!W!OQ!`!TQ!c!XR!h!bQiZQrfTwirQ!Z!QR!d!ZQ!^!RR!f!^Q_RRm_TUOVX!Sv!O!P!WT^R_",
  nodeNames: "⚠ StartTag StartCloseTag MissingCloseTag StartCloseTag StartCloseTag Document Text Comment Element OpenTag TagName Attribute AttributeName Is AttributeValue MismatchedCloseTag CloseTag SelfClosingTag",
  maxTerm: 40,
  context: elementContext,
  nodeProps: [
    [NodeProp.closedBy, 1,"SelfCloseEndTag EndTag",10,"CloseTag MissingCloseTag"],
    [NodeProp.openedBy, 17,"OpenTag"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: "7n!aRzOX#uXZ(lZ]*[]^(l^p#upq(lqr#urs,[sw#uwx,tx}#u}!O-^!O!P#u!P!Q2^!Q![0Y![!^#u!^!_3t!_!`6[!`!a6|!a!c#u!c!}0Y!}#R#u#R#S0Y#S#T#u#T#o0Y#o#y#u#y#z*[#z$f#u$f$g*[$g#BY#u#BY#BZ*[#BZ$IS#u$IS$I_*[$I_$I|#u$I|$JO*[$JO$JT#u$JT$JU*[$JU$KV#u$KV$KW*[$KW&FU#u&FU&FV*[&FV~#u!R$OVVPvps`Or#urs$esw#uwx&Wx!^#u!^!_'b!_~#ua$lTVPs`Ow$ewx${x!^$e!^!_%d!_~$eP%QRVPO!^${!^!_%Z!_~${P%^Qpq${!_!`${a%iUs`Op%{pq$eqw%{x!_%{!_!`$e!`~%{`&QQs`Ow%{x~%{q&_TVPvpOr&Wrs${s!^&W!^!_&n!_~&Wq&sUvpOp'Vpq&Wqr'Vs!_'V!_!`&W!`~'Vp'[QvpOr'Vs~'V!R'iXvps`Op(Upq#uqr(Urs%{sw(Uwx'Vx!_(U!_!`#u!`~(U!Q(]Tvps`Or(Urs%{sw(Uwx'Vx~(U_(sgVPp^OX${X^(l^p${pq(lq!^${!^!_%Z!_#y${#y#z(l#z$f${$f$g(l$g#BY${#BY#BZ(l#BZ$IS${$IS$I_(l$I_$I|${$I|$JO(l$JO$JT${$JT$JU(l$JU$KV${$KV$KW(l$KW&FU${&FU&FV(l&FV~${!a*gkVPvps`p^OX#uX^*[^p#upq*[qr#urs$esw#uwx&Wx!^#u!^!_'b!_#y#u#y#z*[#z$f#u$f$g*[$g#BY#u#BY#BZ*[#BZ$IS#u$IS$I_*[$I_$I|#u$I|$JO*[$JO$JT#u$JT$JU*[$JU$KV#u$KV$KW*[$KW&FU#u&FU&FV*[&FV~#u!T,eTurVPs`Ow$ewx${x!^$e!^!_%d!_~$e!T,}TrbVPvpOr&Wrs${s!^&W!^!_&n!_~&W!a-ka]WZSVPvps`Or#urs$esw#uwx&Wx}#u}!O.p!O!Q#u!Q![0Y![!^#u!^!_'b!_!c#u!c!}0Y!}#R#u#R#S0Y#S#T#u#T#o0Y#o~#u!a.}c]WZSVPvps`Or#urs$esw#uwx&Wx}#u}!O0Y!O!Q#u!Q![0Y![!^#u!^!_'b!_!`#u!`!a1l!a!c#u!c!}0Y!}#R#u#R#S0Y#S#T#u#T#o0Y#o~#u!_0ga]WZSVPvps`Or#urs$esw#uwx&Wx}#u}!O0Y!O!Q#u!Q![0Y![!^#u!^!_'b!_!c#u!c!}0Y!}#R#u#R#S0Y#S#T#u#T#o0Y#o~#u!T1wVmQVPvps`Or#urs$esw#uwx&Wx!^#u!^!_'b!_~#u!Z2gXVPvps`Or#urs$esw#uwx&Wx!^#u!^!_'b!_!`#u!`!a3S!a~#u!Z3_VVPvps`xWOr#urs$esw#uwx&Wx!^#u!^!_'b!_~#u!R3{Xvps`Op(Upq#uqr4hrs%{sw(Uwx'Vx!_(U!_!`#u!`~(U!R4oVvps`Or(Urs%{sw(Uwx'Vx}(U}!O5U!O~(U!R5]Vvps`Or(Urs%{sw(Uwx'Vx}(U}!O5r!O~(U!R5{Tvps`nPOr(Urs%{sw(Uwx'Vx~(U!Z6gV^WVPvps`Or#urs$esw#uwx&Wx!^#u!^!_'b!_~#u!]7XVVPvps`oYOr#urs$esw#uwx&Wx!^#u!^!_'b!_~#u",
  tokenizers: [startTag, commentContent, 0, 1, 2, 3, 4, 5],
  topRules: {"Document":[0,6]},
  tokenPrec: 0
})
