<?PHP
return  array(
        "Coconut",
        "Weeping willow",
        "Sycamore",
        "Beech",
        "Laurel",
        "Dragon tree",
        "Ash",
        "Sequoia",
        "Rubber fig",
        "Birch",
        "Pistachio",
        "Papaya",
        "Cacao tree",
        "Sugar maple",
        "Oak",
        "Silver maple",
        "Adansonia digitata",
        "Blue spruce",
        "Pecan",
        "Walnut",
        "Breadfruit",
        "Magnolia",
        "Quercus ilex",
        "Salix caprea",
        "Tilia cordata",
        "Palm",
        "Larch",
        "Rubber tree",
        "Banyan",
        "Pine",
        "Hemlock",
        "Curry tree",
        "Salix integra",
        "Clove",
        "Tea plant",
        "Brazil nut",
        "Cinnamon tree",
        "Nutmeg",
        "Camphor tree",
        "Elm",
        "Butternut",
        "Cherry",
        "Hawthorn",
        "Hickory",
        "Sassafras",
        "Cedar",
        "Baobab",
);

?>