services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-u",
          "root",
          "-proot_password",
          "-e",
          "USE mydatabase;",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
