export const driveColors=[
  {Color: 'D81159', Name: 'Magenta'},
  {Color: 'F95738', Name: 'Orange'},
  {Color: 'F19143', Name: 'Light orange'},
  {Color: 'C4DEA8', Name: 'Pale green'},
  {Color: '88AB75', Name: 'Green'},
  {Color: '53917E', Name: 'Teal'},
  {Color: '3D5A80', Name: 'Dark Blue'},
  {Color: '81667A', Name: 'Purple'},
  {Color: '546362', Name: 'Dark Gray'},
]

export const driveImages=[
  {Image: 'picture1.jpg', Name: 'Chalkboard'},
  {Image: 'picture2.jpg', Name: 'Clock'},
  {Image: 'picture3.jpg', Name: 'Person writing on tablet'},
  {Image: 'picture4.jpg', Name: 'Green math'},
  {Image: 'picture5.jpg', Name: 'Compass in case'},
  {Image: 'picture6.jpg', Name: 'Person working at computer'},
  {Image: 'picture7.jpg', Name: 'Triangular ruler'},
  {Image: 'picture8.jpg', Name: 'Computer and notebook on desk'},
  {Image: 'picture9.jpg', Name: 'Math on whiteboard'},
  {Image: 'picture10.jpg', Name: 'Two compasses'},
  {Image: 'picture11.jpg', Name: 'Blueprint'},
  {Image: 'picture12.jpg', Name: 'Abacus'},
  {Image: 'picture13.jpg', Name: 'Calculator'},
  {Image: 'picture14.jpg', Name: 'Slide rule'},
  {Image: 'picture15.jpg', Name: 'Side view of abacus'},
  {Image: 'picture16.jpg', Name: 'Blue math'},
]