export const driveColors = [
  { Color: "D81159", Name: "Magenta" },
  { Color: "F95738", Name: "Orange" },
  { Color: "F19143", Name: "Light orange" },
  { Color: "C4DEA8", Name: "Pale green" },
  { Color: "88AB75", Name: "Green" },
  { Color: "53917E", Name: "Teal" },
  { Color: "3D5A80", Name: "Dark Blue" },
  { Color: "81667A", Name: "Purple" },
  { Color: "546362", Name: "Dark Gray" },
];

export const driveImages = [
  { Image: "picture1.jpg", Name: "Orange gradient" },
  { Image: "picture2.jpg", Name: "Teal gradient" },
  { Image: "picture3.jpg", Name: "Light blue gradient" },
  { Image: "picture4.jpg", Name: "Purple gradient" },
  { Image: "picture5.jpg", Name: "Stack of books" },
  { Image: "picture6.jpg", Name: "Drawing of a graph" },
  { Image: "picture7.jpg", Name: "Math on a whiteboard" },
  { Image: "picture8.jpg", Name: "Silver ruler" },
  { Image: "picture9.jpg", Name: "Gray calculator" },
  { Image: "picture10.jpg", Name: "Compass and yellow pen" },
  { Image: "picture11.jpg", Name: "Set of mathematical functions" },
  { Image: "picture12.jpg", Name: "Abacus" },
  { Image: "picture13.jpg", Name: "Calculator on yellow background" },
  { Image: "picture14.jpg", Name: "Triangular ruler" },
  { Image: "picture15.jpg", Name: "Slide rule" },
  { Image: "picture16.jpg", Name: "Blue math" },
  { Image: "picture17.jpg", Name: "Green math" },
  { Image: "picture18.jpg", Name: "Dice" },
  { Image: "picture19.jpg", Name: "Dominoes" },
  { Image: "picture20.jpg", Name: "Set of numbers" },
  { Image: "picture21.jpg", Name: "Part of periodic table and beaker" },
  { Image: "picture22.jpg", Name: "Microscope" },
  { Image: "picture23.jpg", Name: "Set test tubes in beaker" },
  { Image: "picture24.jpg", Name: "Molecule model" },
];
