# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [main, cloud-formation-charles, cloudformation]

env:
  AWS_REGION: "us-east-2"
  WORKING_DIR: ./server
  ECR_REPOSITORY: dev3/doenet

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Setup Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Npm clean install
        run: npm ci
        working-directory: ./server

      - run: npx prisma generate
        working-directory: ./server

      - name: Build
        run: npm run build
        working-directory: ./server

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: "arn:aws:iam::568298704244:role/github-actions-dev3"
          role-skip-session-tagging: true
          # role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: image tag
        id: vars
        shell: bash
        run: |
          sha_short=$(git rev-parse --short HEAD)
          date_string=$(date +%Y-%m-%d-%H-%M-%S)
          tag=${date_string}-${sha_short}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKING_DIR }}
          platforms: linux/amd64
          # build-args: ${{ inputs.build-args }}
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.tag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-to: type=inline
