name: Deploy Doenet Site to Amazon S3

env:
  AWS_REGION: us-east-1
  GHA_ROLE: "arn:aws:iam::568298704244:role/github-actions-dev3"
  AWS_ACCOUNT_ID: 568298704244
  ENV_NAME: dev3

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths:
      - .github/workflows/doenet-site.yml
      - blog/**
      - package.json
      - package-lock.json

permissions:
  id-token: write
  contents: read

jobs:
  doenet-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.GHA_ROLE }}
          role-session-name: site
          aws-region: ${{ env.AWS_REGION }}

      - name: Build the site
        run: |
          npm ci
          cd blog && npm run build

      - name: Sync to S3
        run: |
          aws s3 sync --delete blog/dist s3://${{ env.ENV_NAME }}-site-${{ env.AWS_ACCOUNT_ID }}-${{ env.AWS_REGION }}

      - name: Invalidate CloudFront cache
        run: |
          id=$(aws ssm get-parameter --name "/${{ env.ENV_NAME }}/app/DistributionId" --query "Parameter.Value" --output text)
          aws cloudfront create-invalidation --distribution-id $id --paths "/blog/*" "/_astro/*"
