name: Deploy Doenet Backend to AWS ECR

on:
  push:
    # branches: [main, cloud-formation-charles, cloudformation]

env:
  AWS_REGION: "us-east-2"
  WORKING_DIR: ./server
  ECR_REPOSITORY: dev3/doenet
  ECS_CLUSTER: dev3
  ECS_SERVICE: doenet
  GHA_ROLE: arn:aws:iam::568298704244:role/github-actions-dev3

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  doenet-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Setup Node v24
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Npm clean install
        run: npm ci

      # Generate TS types for Prisma
      - run: npm run prisma:generate --workspace server

      - name: Build server
        run: npm run build --workspace server

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.GHA_ROLE }}
          role-skip-session-tagging: true
          # role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: image tag
        id: vars
        shell: bash
        run: |
          sha_short=$(git rev-parse --short HEAD)
          date_string=$(date +%Y-%m-%d-%H-%M-%S)
          tag=${date_string}-${sha_short}
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKING_DIR }}
          platforms: linux/amd64
          # build-args: ${{ inputs.build-args }}
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.tag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-to: type=inline
      - name: Update the Doenet ECS Service
        uses: ./.github/actions/update-cluster
        with:
          github-actions-role: ${{ env.GHA_ROLE }}
          role-session-name: doenet-backend-ecs
          aws-region: ${{ env.AWS_REGION }}
          ecs-cluster: ${{ env.ECS_CLUSTER }}
          ecs-service: ${{ env.ECS_SERVICE }}
