name: Deploy Doenet Frontend to Amazon S3

env:
  AWS_REGION: us-east-1
  GHA_ROLE: "arn:aws:iam::350646758180:role/github-actions-prod"
  AWS_ACCOUNT_ID: 350646758180
  DOMAIN: prod.doenet.org
  ENV_NAME: prod

on:
  # Making a change
  workflow_dispatch:
  push:
    branches: ["*"] # Later, only `main` or a `production` branch on Doenet org
    paths:
      - .github/**
      - apps/app/**
      - packages/shared/**
      - package.json
      - package-lock.json

permissions:
  id-token: write
  contents: read

jobs:
  doenet-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      WORKING_DIR: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.GHA_ROLE }}
          role-session-name: app
          aws-region: ${{ env.AWS_REGION }}

      - name: Build the project
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          npm ci
          cd apps/app
          npm run build

      - name: Sync to S3
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          aws s3 sync --delete apps/app/dist s3://${{env.ENV_NAME}}-app-${{ env.AWS_ACCOUNT_ID }}-${{ env.AWS_REGION }}
          id=$(aws ssm get-parameter --name "/${{ env.ENV_NAME }}/app/DistributionId" --query "Parameter.Value" --output text)
          aws cloudfront create-invalidation --distribution-id $id --paths "/"
