name: Production - Deploy Doenet Site to Amazon S3

env:
  AWS_REGION: us-east-1
  GHA_ROLE: "arn:aws:iam::350646758180:role/github-actions-prod"
  AWS_ACCOUNT_ID: 350646758180
  ENV_NAME: prod
  BUILD_MODE: prod

on:
  workflow_dispatch:
  push:
    #TODO: remove cloudformation
    branches: ["main", "cloudformation"]
    # paths:
    #   - .github/workflows/prod-deploy-site.yml
    #   - apps/web/**
    #   - package.json
    #   - package-lock.json

permissions:
  id-token: write
  contents: read

jobs:
  doenet-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.GHA_ROLE }}
          role-session-name: site
          aws-region: ${{ env.AWS_REGION }}

      - name: Build the site
        run: |
          npm ci
          cd apps/web && npm run build -- --mode ${{ env.BUILD_MODE }}

      - name: Sync to S3
        run: |
          aws s3 sync --delete apps/web/dist s3://${{ env.ENV_NAME }}-site-${{ env.AWS_ACCOUNT_ID }}-${{ env.AWS_REGION }}

      - name: Invalidate CloudFront cache
        run: |
          id=$(aws ssm get-parameter --name "/${{ env.ENV_NAME }}/app/DistributionId" --query "Parameter.Value" --output text)
          aws cloudfront create-invalidation --distribution-id $id --paths "/blog/*" "/_astro/*"
