name: Reusable - Deploy Doenet Frontend to Amazon S3

on:
  workflow_call:
    inputs:
      deploy_ref:
        description: Git ref or SHA to deploy
        required: true
        type: string
      aws_region:
        description: AWS region for S3 and CloudFront
        required: true
        type: string
      gha_role:
        description: GitHub Actions role ARN
        required: true
        type: string
      aws_account_id:
        description: AWS account ID for bucket naming
        required: true
        type: string
      env_name:
        description: Deployment environment name
        required: true
        type: string
      build_mode:
        description: Frontend build mode
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  doenet-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.deploy_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ inputs.gha_role }}
          role-session-name: app
          aws-region: ${{ inputs.aws_region }}

      - name: Build the project
        run: |
          npm ci
          cd apps/app
          npm run build -- --mode ${{ inputs.build_mode }}

      - name: Sync to S3
        run: |
          aws s3 sync --delete apps/app/dist s3://${{ inputs.env_name }}-app-${{ inputs.aws_account_id }}-${{ inputs.aws_region }}
          id=$(aws ssm get-parameter --name "/${{ inputs.env_name }}/app/DistributionId" --query "Parameter.Value" --output text)
          aws cloudfront create-invalidation --distribution-id $id --paths "/"
